config/routes.rb
Rails.application.routes.draw do
  resources :career_sheets
  get 'career_sheets/delete'
  root to: 'career_sheets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/career_sheet.rb
class CareerSheet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/career_sheets_controller.rb
class CareerSheetsController < ApplicationController
  def index
    @career_sheets = CareerSheet.all
  end

  def show
  end

  def new
    @career_sheets = CareerSheet.new
  end

  def edit
  end

  def create
    @career_sheet = CareerSheet.new(career_sheet_params)
    @career_sheet.save
    flash[:success] = "登録完了しました"
    redirect_to root_path

  end

  def delete
  end

  private
    def career_sheet_params
      params.require(:career_sheet).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/career_sheets_helper.rb
module CareerSheetsHelper
end

app/views/career_sheets/create.html.erb
<h1>CareerSheets#create</h1>
<p>Find me in app/views/career_sheets/create.html.erb</p>

app/views/career_sheets/delete.html.erb
<h1>CareerSheets#delete</h1>
<p>Find me in app/views/career_sheets/delete.html.erb</p>

app/views/career_sheets/edit.html.erb
<h1>スタッフ経歴書 編集</h1>

app/views/career_sheets/index.html.erb
<div class="ui fluid container">
  <div class="row">
    <div class="column ui basic segment">
      <h1 class="ui header">スタッフ経歴書 一覧</h1>

      <table class="ui celled orange table">
      <tr>
        <th>氏名</th>
        <th>会社名</th>
        <th>ステータス</th>
        <th>ユーザ</th>
        <th></th>
        <th></th>
      </tr>
      <% @career_sheets.each do |career_sheet| %>
      <tr>
        <td><%= career_sheet.name %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <% end %>
      </table>
      <%= link_to "+ 経歴書を追加する", new_career_sheet_path %>
    </div>
  </div>
</div>

app/views/career_sheets/new.html.erb
<div class="ui fluid container">
  <div class="row">
    <div class="column ui basic segment">
<h1>スタッフ経歴書 新規登録</h1>

<%= form_with model: @career_sheets, class: 'ui form' do |f| %>

<div class="ui five wide field">
  <%= f.label :name, "イニシャル" %>
  <%= f.text_field :name, placeholder: "" %>
</div>
<div class="ui five wide field">
  <%= f.label :description, "自己PR" %>
  <%= f.text_area :description, placeholder: "" %>
</div>
<div class="ui five wide field">
  <%= f.label :birthday, "誕生日" %>
  <%= f.date_select :birthday, use_month_numbers: true %>
</div>

<%= f.submit '登録', action: "create", class: 'ui red button' %>
<% end %>
    </div>
  </div>
</div>

app/views/career_sheets/show.html.erb
<h1>経歴書詳細</h1>
<%= link_to "+ 経歴書を追加する", new_career_sheet_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CareerManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>